# Generated by Django 4.1.7 on 2023-03-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество комментариев'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(max_length=10000, verbose_name='Фото'),
        ),
    ]
