# Generated by Django 4.1.7 on 2023-03-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(max_length=100000, verbose_name='Фото'),
        ),
    ]
